---
name: Build
on:
  workflow_dispatch:
  push:
    paths:
      - "libft/**"
      - "src/**"
      - "Makefile"
      - "include/**"
      - ".github/workflows/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: make CC=clang
